version: '2'

volumes:
  nextcloud:
  db:
  nextcloud-apps:
  nextcloud-config:
  nextcloud-data:
  mysql-data:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /mnt/writers/mysql-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 80:80
    links:
      - db
    volumes:
      - /mnt/writers/nextcloud-html:/var/www/html
      - /mnt/writers/nextcloud-apps:/var/www/html/apps
      - /mnt/writers/nextcloud-config:/var/www/html/config
      - /mnt/writers/nextcloud-data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
